# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Protos/ibkr.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'Protos/ibkr.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11Protos/ibkr.proto\x12\x04ibkr\"5\n\x11MarketDataRequest\x12\x0e\n\x06symbol\x18\x01 \x01(\t\x12\x10\n\x08\x65xchange\x18\x02 \x01(\t\"C\n\x12MarketDataResponse\x12\x0e\n\x06symbol\x18\x01 \x01(\t\x12\r\n\x05price\x18\x02 \x01(\x01\x12\x0e\n\x06volume\x18\x03 \x01(\x03\"$\n\x0e\x41\x63\x63ountRequest\x12\x12\n\naccount_id\x18\x01 \x01(\t\"6\n\x0f\x41\x63\x63ountResponse\x12\x12\n\naccount_id\x18\x01 \x01(\t\x12\x0f\n\x07\x62\x61lance\x18\x02 \x01(\x01\"T\n\x11PlaceOrderRequest\x12\x0e\n\x06symbol\x18\x01 \x01(\t\x12\x0e\n\x06\x61\x63tion\x18\x02 \x01(\t\x12\x10\n\x08quantity\x18\x03 \x01(\x05\x12\r\n\x05price\x18\x04 \x01(\x01\"H\n\x12PlaceOrderResponse\x12\x10\n\x08order_id\x18\x01 \x01(\t\x12\x0f\n\x07success\x18\x02 \x01(\x08\x12\x0f\n\x07message\x18\x03 \x01(\t\"?\n\x0e\x43onnectRequest\x12\x0c\n\x04host\x18\x01 \x01(\t\x12\x0c\n\x04port\x18\x02 \x01(\x05\x12\x11\n\tclient_id\x18\x03 \x01(\x05\"3\n\x0f\x43onnectResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"\x19\n\x17\x43onnectionStatusRequest\">\n\x18\x43onnectionStatusResponse\x12\x11\n\tconnected\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2\xe4\x02\n\x0bIBKRService\x12\x36\n\x07\x43onnect\x12\x14.ibkr.ConnectRequest\x1a\x15.ibkr.ConnectResponse\x12T\n\x13GetConnectionStatus\x12\x1d.ibkr.ConnectionStatusRequest\x1a\x1e.ibkr.ConnectionStatusResponse\x12G\n\x10StreamMarketData\x12\x17.ibkr.MarketDataRequest\x1a\x18.ibkr.MarketDataResponse0\x01\x12=\n\x0eGetAccountInfo\x12\x14.ibkr.AccountRequest\x1a\x15.ibkr.AccountResponse\x12?\n\nPlaceOrder\x12\x17.ibkr.PlaceOrderRequest\x1a\x18.ibkr.PlaceOrderResponseB\x1b\xaa\x02\x18IBKRAdapterServer.Protosb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Protos.ibkr_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\252\002\030IBKRAdapterServer.Protos'
  _globals['_MARKETDATAREQUEST']._serialized_start=27
  _globals['_MARKETDATAREQUEST']._serialized_end=80
  _globals['_MARKETDATARESPONSE']._serialized_start=82
  _globals['_MARKETDATARESPONSE']._serialized_end=149
  _globals['_ACCOUNTREQUEST']._serialized_start=151
  _globals['_ACCOUNTREQUEST']._serialized_end=187
  _globals['_ACCOUNTRESPONSE']._serialized_start=189
  _globals['_ACCOUNTRESPONSE']._serialized_end=243
  _globals['_PLACEORDERREQUEST']._serialized_start=245
  _globals['_PLACEORDERREQUEST']._serialized_end=329
  _globals['_PLACEORDERRESPONSE']._serialized_start=331
  _globals['_PLACEORDERRESPONSE']._serialized_end=403
  _globals['_CONNECTREQUEST']._serialized_start=405
  _globals['_CONNECTREQUEST']._serialized_end=468
  _globals['_CONNECTRESPONSE']._serialized_start=470
  _globals['_CONNECTRESPONSE']._serialized_end=521
  _globals['_CONNECTIONSTATUSREQUEST']._serialized_start=523
  _globals['_CONNECTIONSTATUSREQUEST']._serialized_end=548
  _globals['_CONNECTIONSTATUSRESPONSE']._serialized_start=550
  _globals['_CONNECTIONSTATUSRESPONSE']._serialized_end=612
  _globals['_IBKRSERVICE']._serialized_start=615
  _globals['_IBKRSERVICE']._serialized_end=971
# @@protoc_insertion_point(module_scope)
