// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: PlaceOrderRequest.proto
// Protobuf C++ Version: 5.29.3

#include "PlaceOrderRequest.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace protobuf {

inline constexpr PlaceOrderRequest::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        contract_{nullptr},
        order_{nullptr},
        orderid_{0} {}

template <typename>
PROTOBUF_CONSTEXPR PlaceOrderRequest::PlaceOrderRequest(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct PlaceOrderRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR PlaceOrderRequestDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~PlaceOrderRequestDefaultTypeInternal() {}
  union {
    PlaceOrderRequest _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PlaceOrderRequestDefaultTypeInternal _PlaceOrderRequest_default_instance_;
}  // namespace protobuf
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_PlaceOrderRequest_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_PlaceOrderRequest_2eproto = nullptr;
const ::uint32_t
    TableStruct_PlaceOrderRequest_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        PROTOBUF_FIELD_OFFSET(::protobuf::PlaceOrderRequest, _impl_._has_bits_),
        PROTOBUF_FIELD_OFFSET(::protobuf::PlaceOrderRequest, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::protobuf::PlaceOrderRequest, _impl_.orderid_),
        PROTOBUF_FIELD_OFFSET(::protobuf::PlaceOrderRequest, _impl_.contract_),
        PROTOBUF_FIELD_OFFSET(::protobuf::PlaceOrderRequest, _impl_.order_),
        2,
        0,
        1,
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, 11, -1, sizeof(::protobuf::PlaceOrderRequest)},
};
static const ::_pb::Message* const file_default_instances[] = {
    &::protobuf::_PlaceOrderRequest_default_instance_._instance,
};
const char descriptor_table_protodef_PlaceOrderRequest_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\027PlaceOrderRequest.proto\022\010protobuf\032\016Con"
    "tract.proto\032\013Order.proto\"\234\001\n\021PlaceOrderR"
    "equest\022\024\n\007orderId\030\001 \001(\005H\000\210\001\001\022)\n\010contract"
    "\030\002 \001(\0132\022.protobuf.ContractH\001\210\001\001\022#\n\005order"
    "\030\003 \001(\0132\017.protobuf.OrderH\002\210\001\001B\n\n\010_orderId"
    "B\013\n\t_contractB\010\n\006_orderBA\n\026com.ib.client"
    ".protobufB\026PlaceOrderRequestProto\252\002\016IBAp"
    "i.protobufb\006proto3"
};
static const ::_pbi::DescriptorTable* const descriptor_table_PlaceOrderRequest_2eproto_deps[2] =
    {
        &::descriptor_table_Contract_2eproto,
        &::descriptor_table_Order_2eproto,
};
static ::absl::once_flag descriptor_table_PlaceOrderRequest_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_PlaceOrderRequest_2eproto = {
    false,
    false,
    298,
    descriptor_table_protodef_PlaceOrderRequest_2eproto,
    "PlaceOrderRequest.proto",
    &descriptor_table_PlaceOrderRequest_2eproto_once,
    descriptor_table_PlaceOrderRequest_2eproto_deps,
    2,
    1,
    schemas,
    file_default_instances,
    TableStruct_PlaceOrderRequest_2eproto::offsets,
    file_level_enum_descriptors_PlaceOrderRequest_2eproto,
    file_level_service_descriptors_PlaceOrderRequest_2eproto,
};
namespace protobuf {
// ===================================================================

class PlaceOrderRequest::_Internal {
 public:
  using HasBits =
      decltype(std::declval<PlaceOrderRequest>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(PlaceOrderRequest, _impl_._has_bits_);
};

void PlaceOrderRequest::clear_contract() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.contract_ != nullptr) _impl_.contract_->Clear();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
void PlaceOrderRequest::clear_order() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.order_ != nullptr) _impl_.order_->Clear();
  _impl_._has_bits_[0] &= ~0x00000002u;
}
PlaceOrderRequest::PlaceOrderRequest(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:protobuf.PlaceOrderRequest)
}
inline PROTOBUF_NDEBUG_INLINE PlaceOrderRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::protobuf::PlaceOrderRequest& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0} {}

PlaceOrderRequest::PlaceOrderRequest(
    ::google::protobuf::Arena* arena,
    const PlaceOrderRequest& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  PlaceOrderRequest* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::uint32_t cached_has_bits = _impl_._has_bits_[0];
  _impl_.contract_ = (cached_has_bits & 0x00000001u) ? ::google::protobuf::Message::CopyConstruct<::protobuf::Contract>(
                              arena, *from._impl_.contract_)
                        : nullptr;
  _impl_.order_ = (cached_has_bits & 0x00000002u) ? ::google::protobuf::Message::CopyConstruct<::protobuf::Order>(
                              arena, *from._impl_.order_)
                        : nullptr;
  _impl_.orderid_ = from._impl_.orderid_;

  // @@protoc_insertion_point(copy_constructor:protobuf.PlaceOrderRequest)
}
inline PROTOBUF_NDEBUG_INLINE PlaceOrderRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void PlaceOrderRequest::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, contract_),
           0,
           offsetof(Impl_, orderid_) -
               offsetof(Impl_, contract_) +
               sizeof(Impl_::orderid_));
}
PlaceOrderRequest::~PlaceOrderRequest() {
  // @@protoc_insertion_point(destructor:protobuf.PlaceOrderRequest)
  SharedDtor(*this);
}
inline void PlaceOrderRequest::SharedDtor(MessageLite& self) {
  PlaceOrderRequest& this_ = static_cast<PlaceOrderRequest&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  delete this_._impl_.contract_;
  delete this_._impl_.order_;
  this_._impl_.~Impl_();
}

inline void* PlaceOrderRequest::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) PlaceOrderRequest(arena);
}
constexpr auto PlaceOrderRequest::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(PlaceOrderRequest),
                                            alignof(PlaceOrderRequest));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull PlaceOrderRequest::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_PlaceOrderRequest_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &PlaceOrderRequest::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<PlaceOrderRequest>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &PlaceOrderRequest::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<PlaceOrderRequest>(), &PlaceOrderRequest::ByteSizeLong,
            &PlaceOrderRequest::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(PlaceOrderRequest, _impl_._cached_size_),
        false,
    },
    &PlaceOrderRequest::kDescriptorMethods,
    &descriptor_table_PlaceOrderRequest_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* PlaceOrderRequest::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 3, 2, 0, 2> PlaceOrderRequest::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(PlaceOrderRequest, _impl_._has_bits_),
    0, // no _extensions_
    3, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967288,  // skipmap
    offsetof(decltype(_table_), field_entries),
    3,  // num_field_entries
    2,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::protobuf::PlaceOrderRequest>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // optional int32 orderId = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(PlaceOrderRequest, _impl_.orderid_), 2>(),
     {8, 2, 0, PROTOBUF_FIELD_OFFSET(PlaceOrderRequest, _impl_.orderid_)}},
    // optional .protobuf.Contract contract = 2;
    {::_pbi::TcParser::FastMtS1,
     {18, 0, 0, PROTOBUF_FIELD_OFFSET(PlaceOrderRequest, _impl_.contract_)}},
    // optional .protobuf.Order order = 3;
    {::_pbi::TcParser::FastMtS1,
     {26, 1, 1, PROTOBUF_FIELD_OFFSET(PlaceOrderRequest, _impl_.order_)}},
  }}, {{
    65535, 65535
  }}, {{
    // optional int32 orderId = 1;
    {PROTOBUF_FIELD_OFFSET(PlaceOrderRequest, _impl_.orderid_), _Internal::kHasBitsOffset + 2, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
    // optional .protobuf.Contract contract = 2;
    {PROTOBUF_FIELD_OFFSET(PlaceOrderRequest, _impl_.contract_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
    // optional .protobuf.Order order = 3;
    {PROTOBUF_FIELD_OFFSET(PlaceOrderRequest, _impl_.order_), _Internal::kHasBitsOffset + 1, 1,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
  }}, {{
    {::_pbi::TcParser::GetTable<::protobuf::Contract>()},
    {::_pbi::TcParser::GetTable<::protobuf::Order>()},
  }}, {{
  }},
};

PROTOBUF_NOINLINE void PlaceOrderRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:protobuf.PlaceOrderRequest)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    if (cached_has_bits & 0x00000001u) {
      ABSL_DCHECK(_impl_.contract_ != nullptr);
      _impl_.contract_->Clear();
    }
    if (cached_has_bits & 0x00000002u) {
      ABSL_DCHECK(_impl_.order_ != nullptr);
      _impl_.order_->Clear();
    }
  }
  _impl_.orderid_ = 0;
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* PlaceOrderRequest::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const PlaceOrderRequest& this_ = static_cast<const PlaceOrderRequest&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* PlaceOrderRequest::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const PlaceOrderRequest& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:protobuf.PlaceOrderRequest)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          cached_has_bits = this_._impl_._has_bits_[0];
          // optional int32 orderId = 1;
          if (cached_has_bits & 0x00000004u) {
            target = ::google::protobuf::internal::WireFormatLite::
                WriteInt32ToArrayWithField<1>(
                    stream, this_._internal_orderid(), target);
          }

          // optional .protobuf.Contract contract = 2;
          if (cached_has_bits & 0x00000001u) {
            target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
                2, *this_._impl_.contract_, this_._impl_.contract_->GetCachedSize(), target,
                stream);
          }

          // optional .protobuf.Order order = 3;
          if (cached_has_bits & 0x00000002u) {
            target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
                3, *this_._impl_.order_, this_._impl_.order_->GetCachedSize(), target,
                stream);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:protobuf.PlaceOrderRequest)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t PlaceOrderRequest::ByteSizeLong(const MessageLite& base) {
          const PlaceOrderRequest& this_ = static_cast<const PlaceOrderRequest&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t PlaceOrderRequest::ByteSizeLong() const {
          const PlaceOrderRequest& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:protobuf.PlaceOrderRequest)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
          cached_has_bits = this_._impl_._has_bits_[0];
          if (cached_has_bits & 0x00000007u) {
            // optional .protobuf.Contract contract = 2;
            if (cached_has_bits & 0x00000001u) {
              total_size += 1 +
                            ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.contract_);
            }
            // optional .protobuf.Order order = 3;
            if (cached_has_bits & 0x00000002u) {
              total_size += 1 +
                            ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.order_);
            }
            // optional int32 orderId = 1;
            if (cached_has_bits & 0x00000004u) {
              total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
                  this_._internal_orderid());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void PlaceOrderRequest::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<PlaceOrderRequest*>(&to_msg);
  auto& from = static_cast<const PlaceOrderRequest&>(from_msg);
  ::google::protobuf::Arena* arena = _this->GetArena();
  // @@protoc_insertion_point(class_specific_merge_from_start:protobuf.PlaceOrderRequest)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x00000007u) {
    if (cached_has_bits & 0x00000001u) {
      ABSL_DCHECK(from._impl_.contract_ != nullptr);
      if (_this->_impl_.contract_ == nullptr) {
        _this->_impl_.contract_ =
            ::google::protobuf::Message::CopyConstruct<::protobuf::Contract>(arena, *from._impl_.contract_);
      } else {
        _this->_impl_.contract_->MergeFrom(*from._impl_.contract_);
      }
    }
    if (cached_has_bits & 0x00000002u) {
      ABSL_DCHECK(from._impl_.order_ != nullptr);
      if (_this->_impl_.order_ == nullptr) {
        _this->_impl_.order_ =
            ::google::protobuf::Message::CopyConstruct<::protobuf::Order>(arena, *from._impl_.order_);
      } else {
        _this->_impl_.order_->MergeFrom(*from._impl_.order_);
      }
    }
    if (cached_has_bits & 0x00000004u) {
      _this->_impl_.orderid_ = from._impl_.orderid_;
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void PlaceOrderRequest::CopyFrom(const PlaceOrderRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:protobuf.PlaceOrderRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void PlaceOrderRequest::InternalSwap(PlaceOrderRequest* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(PlaceOrderRequest, _impl_.orderid_)
      + sizeof(PlaceOrderRequest::_impl_.orderid_)
      - PROTOBUF_FIELD_OFFSET(PlaceOrderRequest, _impl_.contract_)>(
          reinterpret_cast<char*>(&_impl_.contract_),
          reinterpret_cast<char*>(&other->_impl_.contract_));
}

::google::protobuf::Metadata PlaceOrderRequest::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace protobuf
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ PROTOBUF_UNUSED =
        (::_pbi::AddDescriptors(&descriptor_table_PlaceOrderRequest_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
